stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: node:22
  script:
    - echo "Installing dependencies..."
    - npm install || yarn install
    - echo "Building application..."
    - npm run build

test:
  stage: test
  image: node:22
  script:
    - export NODE_PATH=$(npm root -g)
    - echo "Testing application..."
    - npx jest --coverage

pages:
  stage: deploy
  script:
    - echo "Deploying app"
    - mkdir -p public
    - cp -r dist/* public/
  artifacts:
    paths:
      - public
  only:
    - main
    - issue_35_cicd